// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtcrlfikcjfajjlcqopt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Y3JsZmlrY2pmYWpqbGNxb3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODI2ODcsImV4cCI6MjA2OTI1ODY4N30.ShPG9DyobhitHPU0xAirWBtZIR3JIS4nI2WZkD2awtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});