// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwhkxbijdonhwpvkulyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3aGt4YmlqZG9uaHdwdmt1bHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjU1MTgsImV4cCI6MjA2OTM0MTUxOH0.kWeJVTE5_0AOVOEHetT2afKieYx0FyEcjBh-wRg7FYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});